// <auto-generated />
using System;
using CortexTerminal.Gateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


#nullable disable

namespace CortexTerminal.Gateway.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625082948_AddAgentTracking")]
    partial class AddAgentTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);



            modelBuilder.Entity("CortexTerminal.Gateway.Data.ArtifactEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ContentSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_sha256");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("FileCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("file_category");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("origin");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "Filename")
                        .IsUnique();

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("CortexTerminal.Gateway.Data.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_entity");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CortexTerminal.Gateway.Data.SessionAgentEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");



                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAtUtc");

                    b.ToTable("SessionAgentEvents");
                });

            modelBuilder.Entity("CortexTerminal.Gateway.Data.SessionRecordEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("AgentKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("agent_kind");

                    b.Property<string>("AgentSessionId")
                        .HasColumnType("text")
                        .HasColumnName("agent_session_id");

                    b.Property<string>("AttachedClientConnectionId")
                        .HasColumnType("text")
                        .HasColumnName("attached_client_connection_id");

                    b.Property<string>("AttachmentState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attachment_state");

                    b.Property<long>("BytesIngested")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_ingested");

                    b.Property<int>("Columns")
                        .HasColumnType("integer")
                        .HasColumnName("columns");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<string>("ExitReason")
                        .HasColumnType("text")
                        .HasColumnName("exit_reason");

                    b.Property<string>("InferredTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("inferred_title");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("ReplayPending")
                        .HasColumnType("boolean")
                        .HasColumnName("replay_pending");

                    b.Property<int>("Rows")
                        .HasColumnType("integer")
                        .HasColumnName("rows");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkerConnectionId")
                        .HasColumnType("text")
                        .HasColumnName("worker_connection_id");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("worker_id");

                    b.HasKey("SessionId");

                    b.HasIndex("AttachmentState");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CortexTerminal.Gateway.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AppleRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("apple_refresh_token");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("text")
                        .HasColumnName("auth_provider");

                    b.Property<string>("AuthProviderId")
                        .HasColumnType("text")
                        .HasColumnName("auth_provider_id");

                    b.Property<string>("AvatarContentType")
                        .HasColumnType("text")
                        .HasColumnName("avatar_content_type");

                    b.Property<byte[]>("AvatarData")
                        .HasColumnType("bytea")
                        .HasColumnName("avatar_data");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("AuthProvider", "AuthProviderId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CortexTerminal.Gateway.Data.UserIdentity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_provider");

                    b.Property<string>("AuthProviderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_provider_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNormalized")
                        .HasColumnType("text")
                        .HasColumnName("phone_normalized");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("PhoneNormalized");

                    b.HasIndex("UserId");

                    b.HasIndex("AuthProvider", "AuthProviderId")
                        .IsUnique();

                    b.ToTable("UserIdentities");
                });

            modelBuilder.Entity("CortexTerminal.Gateway.Data.UserPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");



                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("CortexTerminal.Gateway.Data.WorkerRecord", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasColumnType("text")
                        .HasColumnName("worker_id");

                    b.Property<string>("Architecture")
                        .HasColumnType("text")
                        .HasColumnName("architecture");

                    b.Property<DateTimeOffset?>("FirstConnectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_connected_at_utc");

                    b.Property<string>("Hostname")
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text")
                        .HasColumnName("operating_system");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("text")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("WorkerId");

                    b.HasIndex("IsOnline");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
